### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by senolfndk** [zt64/Hyperion#22]
not working

**Comment by zt64** [comment]
Could you post the crash, it should be in logcat. I can't do much without it

**Comment by senolfndk** [comment]
> Kazayı gönderebilir misiniz, logcat'te olmalı. onsuz pek yapamam

I don't know how to do it

**Comment by senolfndk** [comment]
https://user-images.githubusercontent.com/52818836/184506438-5d95588a-8056-4b7b-b8e7-5bd6194b94f2.mp4

**Comment by zt64** [comment]
You will need:
- A computer
- ADB installed (<https://streamable.com/h0618w>)
- An unix shell (windows users: use Git Bash or WSL)

1. Enable USB debugging in your phone's developer options
2. Run the following command in a terminal:
```sh
adb logcat -c
```
3. If you have not previously authorized adb on your phone, open it now and authorize your pc
4. Now open OpenCord and reproduce the issue
5. Run the following command again
```sh
adb logcat -d > logcat.txt
```
6. The generated logcat will be in your user home directory

**Comment by daBroma** [comment]
Tried using without the VPN/Adblocker? Also try https://github.com/wingio/Logra or just simple `adb logcat`.

**Comment by senolfndk** [comment]
> VPN/Adblocker olmadan kullanmayı denediniz mi? Ayrıca https://github.com/wingio/Logra veya sadece basit `adb logcat`.
i tried it doesn't work

**Comment by daBroma** [comment]
Logra does not work? `adb logcat` does not work? Care to elaborate?

**Comment by wingio** [comment]
logra needs special permission to read logs from other apps

**Comment by daBroma** [comment]
Shizuku though?

**Comment by wingio** [comment]
doubt they have shizuku installed and set up

**Comment by daBroma** [comment]
Should be easier to setup than `adb shell` on their computer? Since it is a basic app that can use wireless debugging to get `adb shell` permissions?

**Comment by wingio** [comment]
logra also doesn't have exporting yet

**Comment by DiamondMiner88** [comment]
literally just follow what zt said i wrote that for a reason guhhhh
