### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by Fertanima** [zt64/Hyperion#28]
Will the APK be released when the app is finished?

**Comment by daBroma** [comment]
Yes and you can download preview APKs via the Actions tab.

**Comment by Fertanima** [comment]
How?

**Comment by Fertanima** [comment]
I want to download it.

**Comment by daBroma** [comment]
![image](https://user-images.githubusercontent.com/81025171/188278844-673a83ba-165e-4aec-8aa0-7751576f2941.png)
![image](https://user-images.githubusercontent.com/81025171/188278867-31317fa4-77b8-4815-b24b-596ab85cd37d.png)
![image](https://user-images.githubusercontent.com/81025171/188278874-fd4bdc17-421a-46bc-a662-e3423fa6a64d.png)

**Comment by Fertanima** [comment]
Thank you

**Comment by IzzySoft** [comment]
Thanks @daBroma – but that's not exactly intuitive: a "normal user" would never guess that, and most won't check the issues for it either. It would be much better to [tag releases](https://github.com/zt64/Hyperion/releases) and attach the corresponding APKs there, as most projects do.

Further, the APKs in "actions" are debug builds. Wouldn't release builds be more proper for end-users (apart from the fact that `adb backup` won't back up its data anymore then starting with Android 12)?

**Comment by wingio** [comment]
> Thanks @daBroma – but that's not exactly intuitive: a "normal user" would never guess that, and most won't check the issues for it either. It would be much better to [tag releases](https://github.com/zt64/Hyperion/releases) and attach the corresponding APKs there, as most projects do.
> 
> Further, the APKs in "actions" are debug builds. Wouldn't release builds be more proper for end-users (apart from the fact that `adb backup` won't back up its data anymore then starting with Android 12)?

The point of the actions is that they are debug builds, the app isn't anywhere close to done so it doesn't really make sense to use releases.

**Comment by IzzySoft** [comment]
Thanks @wingio – I wasn't aware of that. Totally clear then, and I hope I don't miss when it is ready :wink: All the best!
