### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by senolfndk** [zt64/Hyperion#6]
where can i download the app

**Comment by Ushie** [comment]
https://github.com/zt64/Hyperion/suites/5793951659/artifacts/193438678

**Comment by Importantamigo** [comment]
Method 1 :
• Join the discord server
• Head over to the apk channel and download the last apk and install
Method 2 :
• Sign up or log into your GitHub account
• Go to https://GitHub.com/zt64/Hyperion/actions
• Select the last action and look at artifacts produced at runtime
• Click on the apk to download

**Comment by senolfndk** [comment]
ok
