### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by senolfndk** [zt64/Hyperion#7]
tracking page
automatic update
comments/answers
customizable user interface
custom Player
scrollable suggestions
advanced search
background play
channel page
community posts
sponsorblock interaction
subscription/library page
google sign in

**Comment by zt64** [comment]
These are all already planned

**Comment by senolfndk** [comment]
> Bunların hepsi önceden planlanmış

ok

**Comment by mantikafasi** [comment]
Do not turkish
