### ISSUE TITLE
Hyperion Telegram Channel

### ISSUE THREAD

**Issue by Qaz-7** [zt64/Hyperion#70]
Open a Telegram channel for Hyperion.

**Comment by xafn** [comment]
guh why'd you even close #55

**Comment by daBroma** [comment]
damage in braining

**Comment by Qaz-7** [comment]
> guh why'd you even close #55

The account is no longer mine. I deleted that account for some reason.😱

**Comment by Qaz-7** [comment]
https://t.me/Hyperion2023

**Comment by zt64** [comment]
While telegram is more of a privacy focused app for those people. As a single person team, I do not have the desire, nor capability of maintaining two communities. In the future when Hyperion is more matured then maybe so, but at the time it is not a priority.
