### ISSUE TITLE
I can't search for videos, pause them, etc....

### ISSUE THREAD

**Issue by gallegonovato** [zt64/Hyperion#9]
Good afternoon:

First of all thank you very much for your work and effort.

Download the apk as you put in https://github.com/zt64/Hyperion/issues/6

But the application does not allow me to search for videos. The ones on the main page do not let me pause them. Close them when they are playing. Nor watch another one, I have to close the app so I can watch another one.

I have to close the application so that I can watch another one.

**Comment by zt64** [comment]
Search hasn't been added yet, and playing controls isn't fully done
